version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: egis-rabbitmq
    hostname: egis-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - egis-network

volumes:
  rabbitmq_data: {}

networks:
  egis-network:
    driver: bridge
