version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: egis-redis-stack
    ports:
      - "6379:6379"  
      - "8001:8001"  
    volumes:
      - redis-data:/data
volumes:
  redis-data:
